name: build-docker-image
on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  build-docker-image:
    runs-on: ubuntu-22.04
    # env:
    #   DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
    #   DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }} 
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: build docker image
        uses: ./.github/actions/docker # ./：代表的是這個 GitHub repository 的根目錄
        # 用 with 傳參數給 action.yaml
        with: 
          docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
          docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
          image_name: fastapi-mongo-demo
    
