name: testing
on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  test-code:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: set up py
        with:
          python-version: 3.8

      - name: install requirements
        run: pip install -r requirements.txt

      - name: run py test
        id: run-py-test
        run: pytest
